name: Pre Commit
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    permissions: {}
    strategy:
      matrix:
        path:
          - ./
    steps:
      - name: Pre-Commit
        uses: dasmeta/reusable-actions-workflows/pre-commit@4.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ matrix.path }}
        continue-on-error: true
